[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.lint]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--", "-W", "clippy::pedantic"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--check"]

[tasks.check]
command = "cargo"
args = ["check"]

[tasks.test]
command = "cargo"
args = ["test","--","--skip","time_sensitive"]

[tasks.test_time_sensitive]
env = { "FAKETIME" = "1674054914" }
command = "cargo"
args = ["test","time_sensitive"]

[tasks.test_ci]
dependencies = ["test", "test_time_sensitive"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.ci]
dependencies = ["lint","format","check","test_ci","build"]
