/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NodePcRs {
  hashAlgorithm?: string
  pcr0?: string
  pcr1?: string
  pcr2?: string
  pcr8?: string
}
/**
 * A client can call out to `<enclave-url>/.well-known/attestation` to fetch the attestation doc from the Enclave
 * The fetched attestation doc will have the public key of the domain's cert embedded inside it along with an expiry
 */
export declare function attestEnclave(cert: Buffer, expectedPcrsList: Array<NodePcRs>, attestationDoc: Buffer): boolean
