/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NodePcRs {
  hashAlgorithm?: string
  pcr0?: string
  pcr1?: string
  pcr2?: string
  pcr8?: string
}
/**
 * Deprecated legacy attestation method
 * Supports attesting connections where the attestation doc is embedded in the certs SANs
 */
export function attestConnection(cert: Buffer, expectedPcrsList: Array<NodePcRs>): boolean
/**
 * a client can call out to `<cage-url>/.well-known/attestation` to fetch the attestation doc from the cage
 * The fetched attestation doc will have the public key of the domain's cert embedded inside it along with an expiry
 */
export function attestCage(cert: Buffer, expectedPcrsList: Array<NodePcRs>, attestationDoc: Buffer): boolean
