[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.lint]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--", "-W", "clippy::pedantic"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--check"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.install_deps]
command = "yarn"

[tasks.build]
dependencies = ["clean","install_deps"]
command = "yarn"
args = ["run", "build"]

[tasks.add_lib_faketime]
script = '''
sudo apt-get install -y libfaketime
'''

[tasks.test]
dependencies = ["build", "add_lib_faketime"]
env = { "LD_PRELOAD" = "/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1", "FAKETIME" = "2023-01-18 15:15:00" }
command = "yarn"
args = ["test"]

[tasks.ci]
dependencies = ["lint","format","test"]
